### ISSUE TITLE
Will the signature for `uv_fs_scandir` be changing?

### ISSUE THREAD

**Issue by techno-express** [amphp/ext-uv#82]
You have at:
https://github.com/bwoebi/php-uv/blob/0b40ad9f512953c1c5c00d9637732891516a703c/php_uv.c#L5859

The signature listed at http://docs.libuv.org/en/v1.x/fs.html#c.uv_fs_scandir shows:
`uv_fs_scandir(uv_loop_t* loop, uv_fs_t* req, const char* path, int flags, uv_fs_cb cb)`

Currently, the example `readdir.php` throws `PHP Warning:  uv_fs_scandir() expects parameter 3 to be integer, object given in ...`

Works correctly once switched around.

**Comment by CharlotteDunois** [comment]
The callback signature was changed with commit `e76ac0dccb7908181ee715326e4f8061b77712f6`. The example is for the new version v0.3.0 (not released yet), while previous versions had first the flags and then the callback.

I've had to update my library too, to temporarily support both v0.2.4 and git builds.
<https://github.com/AndromedaGalaxy/reactphp-libuv-filesystem/commit/a48e67a68779a72876fe4c4e9ccb05f26431a13b#diff-6cccbfd4d0d4ee5eb861b1256b5fad51R343>

Once v0.3.0 is released, I'll however drop support for v0.2.4, since there are some unavoidable segfaults and missing features with that version.
